--CREATE TABLE [dbo].[CampaignSessions]
--(
--	[CampaignId] INT NOT NULL , 
--    [SessionId] INT NOT NULL,
--	CONSTRAINT [FK_Campaign_Session_CampaignId] FOREIGN KEY(CampaignId) REFERENCES Campaign(Id),
--    CONSTRAINT [FK_Campaign_Session_SessionId] FOREIGN KEY(SessionId) REFERENCES Session(Id), 
--	CONSTRAINT [PK_CampaignSessions] PRIMARY KEY ([CampaignId], [SessionId])
--)
