//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public int ParentMapId { get; set; }
        public Nullable<int> ChildMapId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Map Map1 { get; set; }
    }
}
